In [2]:
#1. Import the NUMPY package under the name np.

#[your code here]
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.

#[your code here]
print(np.__version__)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Usuario/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Usuario/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Usuario/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

#[your code here]
a = np.random.randint(6,size=(2,3,5))

In [5]:
#4. Print a.

#[your code here]
print(a)

[[[2 2 2 3 3]
  [4 5 0 1 0]
  [4 4 0 1 4]]

 [[1 2 3 4 4]
  [4 3 1 1 0]
  [4 4 0 1 4]]]


In [6]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

#[your code here]
b=np.full((5,2,3),1)

In [7]:
#6. Print b.

#[your code here]
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [8]:
#7. Do a and b have the same size? How do you prove that in Python code?

#[your code here]
b.size == a.size

True

In [9]:
#8. Are you able to add a and b? Why or why not?

#[your code here]
print(a+b)
#No se pueden juntar porque no tienen la misma forma a pesar de tener el mismo tamaño

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [10]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

#[your code here]
c = b.transpose(1,2,0)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [11]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

#[your code here]
d = a+c 
#no funciona a no ser que hagas un cambio en la forma de la matriz, no se si es que el enunciado está mal o que realmente debíamos hacer el cambio

In [12]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
#No entiendo la pregunta
#[your code here]
print(a)

print(d)

[[[2 2 2 3 3]
  [4 5 0 1 0]
  [4 4 0 1 4]]

 [[1 2 3 4 4]
  [4 3 1 1 0]
  [4 4 0 1 4]]]
[[[3 3 3 4 4]
  [5 6 1 2 1]
  [5 5 1 2 5]]

 [[2 3 4 5 5]
  [5 4 2 2 1]
  [5 5 1 2 5]]]


In [13]:
#12. Multiply a and c. Assign the result to e.

#[your code here]
e = a*c
print(e)

[[[2 2 2 3 3]
  [4 5 0 1 0]
  [4 4 0 1 4]]

 [[1 2 3 4 4]
  [4 3 1 1 0]
  [4 4 0 1 4]]]


In [14]:
#13. Does e equal to a? Why or why not?
#Porque C es una matriz del mismo tamaño con solo unos. Por lo que un número multiplicado por uno es uno. 
#[your code here]
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [21]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

#[your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

6
1
3.3666666666666667


In [23]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

#[your code here]
f = np.empty((2,3,5)) #No entiendo porque no me la printea empty
f

array([[[6.93271349e-312, 6.93248726e-312, 0.00000000e+000,
         0.00000000e+000, 1.30617774e-178],
        [1.16097020e-028, 1.26104862e-076, 3.17976463e-028,
         2.52455712e-052, 1.04917183e-153],
        [5.23081515e-143, 2.65626471e+179, 1.82843570e+184,
         4.65637181e-033, 2.03897925e+160]],

       [[7.43321343e-144, 3.59751658e+252, 1.46901661e+179,
         8.37404147e+242, 4.31999013e-096],
        [4.82337723e+228, 3.99448902e+175, 4.46364060e-033,
         5.45007129e-090, 4.27930901e-033],
        [6.46078314e+170, 5.04621343e+180, 1.94918963e-153,
         1.14484251e+243, 2.59903827e-144]]])

In [19]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

#[your code here] -- (no me sale, no estoy entendiendo nada.... He probado de diferentes manera y al final he hecho lo que ponía el chatgpt. Pero todo me da error.
print(d)
for i in range(len(d)):
    for j in range(len(d[i])):
        if d_min < d[i][j] < d_mean:
            f[i][j] = 25
        elif d_mean < d[i][j] < d_max:
            f[i][j] = 75
        elif d[i][j] == d_mean:
            f[i][j] = 50
        elif d[i][j] == d_min:
            f[i][j] = 0
        elif d[i][j] == d_max:
            f[i][j] = 100
print(f)

[[[3 3 3 4 4]
  [5 6 1 2 1]
  [5 5 1 2 5]]

 [[2 3 4 5 5]
  [5 4 2 2 1]
  [5 5 1 2 5]]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [71]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

#[your code here]

'\n#17. Print d and f. Do you have your expected f?\nFor instance, if your d is:\narray([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],\n        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],\n        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],\n\n       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],\n        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],\n        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])\n\nYour f should be:\narray([[[ 75.,  75.,  75.,  25.,  75.],\n        [ 75.,  75.,  25.,  25.,  25.],\n        [ 75.,  25.,  75.,  75.,  75.]],\n\n       [[ 25.,  25.,  25.,  25., 100.],\n        [ 75.,  75.,  75.,  75.,  75.],\n        [ 25.,  75.,   0.,  75.,  75.]]])\n'

In [19]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

#[your code here]

'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'